allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram
