import type { PayloadAction, Selector } from "@reduxjs/toolkit";
import { createSelector, createSlice } from "@reduxjs/toolkit";
import { LatLngBounds } from "leaflet";

import { mapCatalogByProperty, pivotTable, shuffleArray } from "src/lib/utils";
import type { CountriesByContinent, CountryCatalog, CountryData } from "src/store/CountryStore/types";
import type { AppThunk, RootState } from "..";

import continentData from "src/assets/data/features/continent-features.json";
import countryData from "src/assets/data/features/country-features.json";

export const continentBoundsCatalog = mapCatalogByProperty(
  continentData,
  (item) => item.CONTINENT,
  (item) => {
    // The bounds are generated by MapShaper in different order than what Leaflet expects
    // See: https://github.com/mbloch/mapshaper/blob/master/REFERENCE.md#-each
    const [west = 0, south = 0, east = 0, north = 0] = item.BBOX;
    return new LatLngBounds([south, west], [north, east]);
  },
);

export const countryCatalog: CountryCatalog = mapCatalogByProperty(
  countryData,
  ({ GU_A3 }) => GU_A3,
  (item) => item,
);
export const countriesByContinent: CountriesByContinent = pivotTable(countryCatalog, "CONTINENT", ({ GU_A3 }) => GU_A3);
export const continents = [...Object.keys(countriesByContinent).sort()] as const;

export type ActivityState = {
  queue: string[];
  visitedCountries: string[];
  shuffle: boolean;
};

type CountryStoreState = {
  quiz: ActivityState;
  review: ActivityState;
};

export type ActivityType = keyof CountryStoreState;

export const initialState: CountryStoreState = {
  quiz: {
    queue: [],
    visitedCountries: [],
    shuffle: true,
  },
  review: {
    queue: [],
    visitedCountries: [],
    shuffle: true,
  },
};

const countryStoreSlice = createSlice({
  name: "countryStore",
  initialState,
  reducers: {
    clearCountriesQueue(state, { payload: activityType }: PayloadAction<ActivityType>) {
      state[activityType].queue = [];
    },

    setCountryStoreState(
      state,
      {
        payload: { activityType, newState },
      }: PayloadAction<{ activityType: ActivityType; newState: Partial<ActivityState> }>,
    ) {
      state[activityType] = { ...state[activityType], ...newState };
    },

    resetCountryStoreState(state, { payload: activityType }: PayloadAction<ActivityType>) {
      const activity = state[activityType];
      activity.queue = [];
      activity.visitedCountries = [];
    },

    addVisitedCountry(
      state,
      { payload: { countryCode, activityType } }: PayloadAction<{ countryCode: string; activityType: ActivityType }>,
    ) {
      state[activityType].visitedCountries.push(countryCode);
    },
  },
});

export const { clearCountriesQueue, addVisitedCountry } = countryStoreSlice.actions;
export default countryStoreSlice.reducer;

type CreateQueuePayload = {
  activityType: ActivityType;
  continent: keyof typeof countriesByContinent;
  shuffle: boolean;
};

export function createQueue({ activityType, continent, shuffle }: CreateQueuePayload): AppThunk<CountryData | null> {
  return function (dispatch) {
    let newQueue = continent ? (countriesByContinent[continent]?.slice() ?? []) : [];

    if (shuffle) {
      newQueue = shuffleArray(newQueue);
    } else {
      newQueue.sort();
    }

    const nextCountryCode = newQueue[0];

    dispatch(
      countryStoreSlice.actions.setCountryStoreState({
        activityType,
        newState: {
          queue: newQueue,
          visitedCountries: [],
          shuffle,
        },
      }),
    );

    if (!nextCountryCode) return null;

    const nextCountryData = countryCatalog[nextCountryCode];
    if (!nextCountryData) return null;

    return nextCountryData;
  };
}

export function popNextCountry(activityType: ActivityType): AppThunk<CountryData | null> {
  return function (dispatch, getState) {
    const { countryStore } = getState();
    const { visitedCountries, queue } = countryStore[activityType];

    if (queue.length === 0) return null;

    const nextCountry = queue[0];

    if (!nextCountry) return null;

    dispatch(
      countryStoreSlice.actions.setCountryStoreState({
        activityType,
        newState: {
          queue: queue.slice(1),
          visitedCountries: [...visitedCountries, nextCountry],
        },
      }),
    );

    const nextCountryData = countryCatalog[nextCountry];
    if (!nextCountryData) return null;

    return nextCountryData;
  };
}

export function changeCurrentCountry({
  activityType,
  countryCode,
}: {
  activityType: ActivityType;
  countryCode: string;
}): AppThunk<CountryData | null> {
  return function (dispatch, getState) {
    const { visitedCountries, queue } = getState().countryStore[activityType];
    const currentCountry = queue[0];

    if (currentCountry === countryCode) return null;

    dispatch(
      countryStoreSlice.actions.setCountryStoreState({
        activityType,
        newState: {
          queue: [countryCode, ...queue.filter((c) => c !== countryCode)],
          visitedCountries: visitedCountries.filter((c) => c !== countryCode),
        },
      }),
    );

    const countryData = countryCatalog[countryCode];
    if (!countryData) return null;

    return countryData;
  };
}

export function resetActivity(activityType: ActivityType): AppThunk {
  return function (dispatch) {
    dispatch(countryStoreSlice.actions.resetCountryStoreState(activityType));
  };
}

export function restartCountryQueue(activityType?: ActivityType): AppThunk {
  return function (dispatch, getState) {
    if (!activityType) return;

    const { queue } = getState().countryStore[activityType];

    const currentCountryCode = queue[0];
    const currentCountry = currentCountryCode ? countryCatalog[currentCountryCode] : undefined;

    if (!currentCountryCode || !currentCountry) return;

    const continent = currentCountryCode ? currentCountry.CONTINENT : null;

    if (!continent) return;

    dispatch(resetActivity(activityType));
    dispatch(createQueue({ activityType, continent, shuffle: true }));
  };
}

export function selectCurrentCountryCode(activity?: ActivityType): (state: RootState) => string | null {
  return ({ countryStore }) => (activity ? (countryStore[activity].queue[0] ?? null) : null);
}

export function selectNextCountry(activity?: ActivityType): Selector<RootState, CountryData | null> {
  return createSelector(
    ({ countryStore }: RootState) => (activity ? countryStore[activity].queue[0] : null),
    (country) => (country ? (countryCatalog[country] ?? null) : null),
  );
}

export function selectCurrentCountryData(activityType?: ActivityType): Selector<RootState, CountryData | null> {
  return createSelector(
    ({ countryStore }: RootState) => (activityType ? countryStore[activityType] : null),
    (activityState) => {
      const countryCode = activityState?.queue[0];

      if (!countryCode) return null;

      return countryCatalog[countryCode] ?? null;
    },
  );
}

export function selectCurrentContinent(activityType?: ActivityType): Selector<RootState, string | null> {
  return createSelector(
    ({ countryStore }: RootState) => (activityType ? countryStore[activityType] : null),
    (state) => {
      const countryCode = state?.queue[0];
      if (!countryCode) return null;

      const country = countryCatalog[countryCode];
      if (!country) return null;

      return country.CONTINENT;
    },
  );
}
